### ISSUE TITLE
Multiple tests on same model fails

### ISSUE THREAD

**Issue by AndreasTA-AW** [mjirv/dbt-datamocktool#17]
### Describe the bug
When I add multiple unit tests for the same model, they both seem to go towards the same "xxx__dbt_tmp" table. But they should have different answers. This makes the tests fail.

### Steps to reproduce
Add 2 unit tests to the same model with different input and output.

### Expected results
Both tests should run and have their own result from the base table.

### Actual results
Always one of the tests fail, randomly depending on who did the __dbt_tmp table first I guess?

### System information
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.3
  - package: mjirv/dbt_datamocktool
    version: [">=0.1.4"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.1
```

Not sure if I'm doing something wrong, but when I've rerun a few times this seems to be the problem, the tmp table contains one of the tables expected output and they are both using the same one.
