### ISSUE TITLE
Using aliases

### ISSUE THREAD

**Issue by AndreasTA-AW** [mjirv/dbt-datamocktool#23]
### Describe the bug
Not sure if this is a bug, but we use aliases and when we do, this library can't find the model, since the model itself is still called what the sql file is called and the alias just exists inside of that model.

### Steps to reproduce
Rename a model with {{config(alias='something_else')}}

### Expected results
Run the tests

### Actual results
'dict object' has no attribute 'model.<dbt_project_name>.<alias\>'

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.3
  - package: mjirv/dbt_datamocktool
    version: [">=0.1.5"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.21.0
```
