### ISSUE TITLE
All tests doesn't run

### ISSUE THREAD

**Issue by AndreasTA-AW** [mjirv/dbt-datamocktool#41]
### Describe the bug
I've added a new test in a yml file but when I run `dbt test.....` it only run my old tests.

### Steps to reproduce
I basically just added a new 
```
tests:
      - dbt_datamocktool.unit_test:
          input_mapping:
            ref('xx'): ref('yy')
            source('xxx', 'xxxx'): ref('yyyy')
          expected_output: ref('xxx')
          name: "xxx"
          description: "xxxx"

### Expected results
Run the new test as well :)

### Actual results
The test doesn't run at all.

### System information
**The contents of your `packages.yml` file:**

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.2
  - package: mjirv/dbt_datamocktool
    version: [">=0.1.9"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 1.0.3
   latest version: 1.0.3

Up to date!

Plugins:
  - bigquery: 1.0.0 - Up to date!
```

Maybe I'm missing something here?
