### ISSUE TITLE
SQL Server bug: Views or functions are not allowed on temporary tables

### ISSUE THREAD

**Issue by mjirv** [mjirv/dbt-datamocktool#42]
### Describe the bug
See https://getdbt.slack.com/archives/C01UM2N7814/p1646744516633119

### Steps to reproduce
```yaml
- name: My_model
    tests:
      - dbt_datamocktool.unit_test:
          input_mapping:
            source('<schema>','<My_model_raw>'): ref('dmt__input')
          expected_output: ref('dmt__expected_output')
```

### Screenshots and log output
```
Views or functions are not allowed on temporary tables. Table names that begin with '#' denote temporary tables. (4508)
```

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (SQL Server)

**The output of `dbt --version`:**
```
<output goes here>
```
