### ISSUE TITLE
How to mock {{ this }} macro?

### ISSUE THREAD

**Issue by yauhen-sobaleu** [mjirv/dbt-datamocktool#49]
Hello!

Reading the documentation I did not understand whether there is a way to mock not only "sources and refs" but also `{{ this }}` dbt macro if a model uses it?

**Comment by gwalterr** [comment]
I had success adding `this` straight to `input_mapping`:

```yaml
models:
  - name: ...
    tests:
      - dbt_datamocktool.unit_test:
          input_mapping:
            this: ref('dmt__...')
          expected_output: ref('dmt__...')
```

Reading through this helped me understand what's going on:

https://github.com/mjirv/dbt-datamocktool/blob/866da13d8d39d2e3a5417ff4cfb7d53c1c01c825/macros/dmt_get_test_sql.sql#L8-L11

https://github.com/mjirv/dbt-datamocktool/blob/866da13d8d39d2e3a5417ff4cfb7d53c1c01c825/macros/dmt_get_test_sql.sql#L26-L29
