### ISSUE TITLE
Pattern for multiple test cases, avoiding repetition in the yaml file

### ISSUE THREAD

**Issue by marcellovictorino** [mjirv/dbt-datamocktool#53]
### Describe the feature
I would like to be able to define the dbt_datamocktool test using placeholder values, so multiple test cases can be captured by different input/output seeds, but without requiring repetition in the yaml file

### Describe alternatives you've considered
I can achieve this by copying and pasting the entire dbt_datamocktool test block, applying the specific input mapping/expected output for each seed

Example:
```yaml
models:
  - name: model_name_here
     tests:
      - dbt_datamocktool.unit_test:
          tags: 
            - topic_unit_test 
          input_mapping:
            ref('existing_model'): ref('existing_model__input__test_case_{{ i }}')
          expected_output: ref('expect__existing_model__test_case_{{ i }}')
```
So, for each test case I have to copy-and-paste the entire block only to replace `{{i}}` with the specific test case number

### Additional context
N/A

### Who will this benefit?
This benefits all users with real case applications/complex logic.
By splitting the test into multiple test cases, it is easy to come up with the test data/output; as well as easily identify which specific test/logic is failing

### Are you interested in contributing this feature?
I would love to contribute extending this feature. Not sure what is the best way to approach it though.
I imagine it would be possible to parameterise the underlying datamocktool macro to receive an additional and optional parameter with a list of values

> Note: due to a current legacy project using dbt version 0.19.2, I am using datamocktool revision 0.1.2 (from this repo)

**Comment by marcellovictorino** [comment]
Update [2022-09-29]:
@mjirv I have implemented this functionality for my own project. I would be happy to raise a PR if this is deemed as a feasible contribution
It is backwards compatible as well, so should be safe to implement. Let me know if I should raise a PR

**Comment by marcellovictorino** [comment]
Sure thing!
The model yaml, with test applied at the table level looks like the following:
```yaml
- name: domain_x__report_name
  tests:
    - custom_unit_test:
        tags: 
          - domain_x_unit_test 
        test_case_list: [9,12,27,28,29,30]
        input_mapping:
          ref('model_name1'): \ref('model_name1__input__test_case_@')
          ref('model_nam2'): \ref('model_name2__input__test_case_@')
        expected_output: \ref('expect__report_name__test_case_@')
```
The documentation provides instructions, but basically:
* If not using the optional field `test_case_list`, the test behaves as usual
* if `test_case_list`, it replaces the `@` with each value in the iterator list

> Note: I had to use the `\` to escape the key, in order to treat it as a string (replacing with the `@` symbol) before rendering the full Relation/Path (database.schema.identifier)

This results in a single dbt test. In case of failures, it returns the count of mismatching records.
It also logs the name of each failing test case

Lastly, I noticed there was no visibility on the unit test errors.
So I changed the process to also materialize the output of the model, using the mocked input. It gets stored as a view, making it easy to look at the underlying code by inspecting the view definition.

This has really helped debugging failing unit tests and increasing code coverage.

Would be interested to hear your thoughts on these approaches. I will raise a PR tomorrow, so you can have a closer look 👍
