### ISSUE TITLE
Comparing all columns fails

### ISSUE THREAD

**Issue by santicapchase** [mjirv/dbt-datamocktool#60]
### Describe the bug
As far as I know, when we son't specify the columns to compare in the `compare_columns`, all columns should be compared. When the code for the test is generated, a `*` should be added, but this is just not the case sometimes... Which results in the test failing. (screenshot below)

### Steps to reproduce
I'm not exactly sure how to reproduce the issue, as this is pretty flaky and seems to fail randomly (I haven't been able to find a pattern as of now).

### Screenshots and log output

![Screenshot from 2022-12-02 18-05-57](https://user-images.githubusercontent.com/91610731/207305377-caff8cc1-78e1-485d-9b79-f470e21b96f0.png)

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: mjirv/dbt_datamocktool
    version: 0.2.0
  - package: re-data/re_data
    version: 0.10.1
  - package: calogica/dbt_expectations
    version: 0.5.6
  - package: dbt-labs/codegen
    version: 0.6.0
  - package: dbt-labs/dbt_utils
    version: 0.8.6
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.3
  - latest:    1.3.1 - Update available!
  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
Plugins:
  - bigquery: 1.2.0 - Update available!
  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Are you interested in contributing the fix?

Maybe not specifically me, but someone from my org could probably help
